version: "3"

vars:
  BIN_NAME: skycli
  BIN_DIR: tmp
  BIN_PATH: "{{.BIN_DIR}}/{{.BIN_NAME}}"
  CMD_PACKAGE: ./cli/cmd
  PACKAGES: ./...

env:
  GO111MODULE: "on"

tasks:
  default:
    desc: Run formatting, vet, and tests
    cmds:
      - task: check

  check:
    desc: Format, vet, and test the Go codebase
    cmds:
      - task: fmt
      - task: vet
      - task: test

  fmt:
    desc: Format Go source files
    cmds:
      - go fmt {{.PACKAGES}}
    preconditions:
      - sh: command -v go
        msg: Go toolchain is required

  vet:
    desc: Run go vet on all packages
    cmds:
      - go vet {{.PACKAGES}}
    preconditions:
      - sh: command -v go
        msg: Go toolchain is required

  test:
    desc: Execute Go test suite
    cmds:
      - go test {{.PACKAGES}}
    preconditions:
      - sh: command -v go
        msg: Go toolchain is required

  build:
    desc: Build the CLI binary
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_PATH}} {{.CMD_PACKAGE}}
    sources:
      - go.mod
      - go.sum
      - cli/**/*.go
    generates:
      - "{{.BIN_PATH}}"
    preconditions:
      - sh: command -v go
        msg: Go toolchain is required

  run:
    desc: Run the CLI with optional arguments (pass via `task run -- <args>`)
    cmds:
      - >
        go run {{.CMD_PACKAGE}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v go
        msg: Go toolchain is required

  tidy:
    desc: Ensure go.mod and go.sum are up to date
    cmds:
      - go mod tidy
    preconditions:
      - sh: command -v go
        msg: Go toolchain is required

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}
